using iLand.Tools;
using System;
using System.Collections.Generic;

namespace iLand.Tree
{
    public class SaplingGrowthParameters
    {
        public double BrowsingProbability { get; set; }
        public float HdSapling { get; set; } // fixed height-diameter ratio used for saplings
        public Expression HeightGrowthPotential { get; private set; } // formula that expresses height growth potential
        public int MaxStressYears { get; set; } // trees die, if they are "stressed" for this number of consectuive years
        public double ReferenceRatio { get; set; } // f_ref (eq. 3) -> ratio reference site / optimum site
        public float ReinekesR { get; set; } // Reinekes R, i.e. maximum stem number for a dg of 25cm
        public List<float> RepresentedClasses { get; private set; } // lookup table for represented trees
        public float SproutGrowth { get; set; } // multiplier of growth for saplings regenerated by sprouts (0: no sprouts)
        public float StressThreshold { get; set; } // tree is considered as "stressed" if f_env_yr is below that threhold

        public SaplingGrowthParameters()
        {
            this.BrowsingProbability = 0.0;
            this.HdSapling = 80.0F;
            this.HeightGrowthPotential = new Expression();
            this.MaxStressYears = 3;
            this.ReinekesR = 1450.0F;
            this.ReferenceRatio = 1.0;
            this.RepresentedClasses = new List<float>();
            this.SproutGrowth = 0.0F;
            this.StressThreshold = 0.1F;
        }

        /// represented stem number by height of one cohort (using Reinekes Law): this uses a lookup table to improve performance
        public float RepresentedStemNumberFromHeight(float height)
        {
            return this.RepresentedClasses[Global.Limit((int)MathF.Round(10.0F * height), 0, this.RepresentedClasses.Count)];
        }

        /// represented stem number by one cohort (using Reinekes Law):
        public float RepresentedStemNumberFromDiameter(float dbh)
        {
            return this.ReinekesR * MathF.Pow(dbh / 25.0F, -1.605F) / Constant.LightCellsPerHectare;
        }

        /// browsing probability
        public void SetupReinekeLookup()
        {
            // BUGBUG: constants?
            this.RepresentedClasses.Clear();
            for (int heightClass = 0; heightClass < 41; ++heightClass)
            {
                float height = heightClass / 10.0F + 0.05F; // 0.05, 0.15, 0.25, ... 4.05
                float dbh = 100.0F * height / this.HdSapling;
                this.RepresentedClasses.Add(RepresentedStemNumberFromDiameter(dbh));
            }
        }
    }
}
