library(arrow)
library(dplyr)
library(ggplot2)
library(patchwork)

theme_set(theme_bw() + theme(axis.line = element_line(size = 0.5),
                             legend.background = element_rect(fill = alpha("white", 0.5)),
                             legend.margin = margin(),
                             panel.border = element_blank()))

# read .feather files generated by powerShellTests.ps
elliottIndividualTreeTrajectories = read_feather("TestResults/Elliott individual tree trajectories.feather", mmap = FALSE) %>%
  mutate(species = factor(species, labels = c("all", "psme"), levels = c(0, 202)))
elliottResourceUnitTrajectories = read_feather("TestResults/Elliott resource unit trajectories.feather", mmap = FALSE) %>%
  mutate(qmd = sqrt(basalArea / (0.01^2 * pi/4 * treesPerHectare)),
         species = factor(species, labels = c("all", "psme"), levels = c(0, 202)))
elliottStandTrajectories = read_feather("TestResults/Elliott stand trajectories.feather", mmap = FALSE) %>%
  mutate(qmd = sqrt(basalArea / (0.01^2 * pi/4 * treesPerHectare)))

## basic check plots
# Reineke stand density diagrams by resource unit and stand (with workaround for https://github.com/tidyverse/ggplot2/issues/4935)
ggplot(elliottResourceUnitTrajectories %>% filter(species == "all")) +
  geom_path(aes(x = treesPerHectare, y = qmd, group = resourceUnit), arrow = arrow(length = unit(0.25, "line"), type = "closed")) +
  geom_path(aes(x = treesPerHectare, y = qmd, color = liveStemVolume, group = resourceUnit)) +
  labs(x = "resource unit TPH", y = "resource unit all species QMD, cm", color = bquote("live stem\nvolume, m"^3*" ha"^-1)) +
  theme(legend.justification = c(1, 1), legend.position = c(0.99, 0.97))
ggplot(elliottResourceUnitTrajectories %>% filter(species == "psme")) +
  geom_path(aes(x = treesPerHectare, y = qmd, group = resourceUnit), arrow = arrow(length = unit(0.25, "line"), type = "closed")) +
  geom_path(aes(x = treesPerHectare, y = qmd, color = liveStemVolume, group = resourceUnit)) +
  labs(x = "resource unit TPH", y = "resource unit Douglas-fir QMD, cm", color = bquote("live stem\nvolume, m"^3*" ha"^-1)) +
  theme(legend.justification = c(1, 1), legend.position = c(0.99, 0.97))
ggplot(elliottStandTrajectories) +
  geom_path(aes(x = treesPerHectare, y = qmd, group = stand), arrow = arrow(length = unit(0.25, "line"), type = "closed")) +
  geom_path(aes(x = treesPerHectare, y = qmd, color = liveStemVolume, group = stand)) +
  labs(x = "stand TPH", y = "stand QMD, cm", color = bquote("live stem\nvolume, m"^3*" ha"^-1)) +
  theme(legend.justification = c(1, 1), legend.position = c(0.99, 0.97))

# height-diameter trajectories
individualTreeSubset = elliottIndividualTreeTrajectories %>% filter(id %in% sample(unique(id), size = 250))
ggplot(individualTreeSubset) + # rather slow to plot all ~25 k trees
  geom_line(aes(x = dbh, y = height, color = species, group = id), alpha = 0.3, arrow = arrow(length = unit(0.25, "line"), type = "closed")) +
  labs(x = "individual tree DBH, cm", y = "individual tree height, m", color = NULL) +
  theme(legend.justification = c(0, 1), legend.position = c(0.02, 0.99))
#library(writexl)
#write_xlsx(individualTreeSubset, "TestResults/Elliott individual tree subset.xlsx")
ggplot(elliottResourceUnitTrajectories %>% filter(species == "all")) +
  geom_path(aes(x = averageDbh, y = averageHeight, group = resourceUnit), arrow = arrow(length = unit(0.25, "line"), type = "closed")) +
  geom_path(aes(x = averageDbh, y = averageHeight, color = basalArea, group = resourceUnit)) +
  labs(x = "resource unit mean DBH, cm", y = "resource unit mean tree height, m", color = bquote(atop("basal area,", "m"^2*" ha"^-1))) +
  theme(legend.justification = c(1, 0), legend.position = c(0.99, 0.02))
ggplot(elliottStandTrajectories) +
  geom_path(aes(x = averageDbh, y = averageHeight, group = stand), arrow = arrow(length = unit(0.25, "line"), type = "closed")) +
  geom_path(aes(x = averageDbh, y = averageHeight, color = basalArea, group = stand)) +
  labs(x = "stand mean DBH, cm", y = "stand mean tree height, m", color = bquote(atop("basal area,", "m"^2*" ha"^-1))) +
  theme(legend.justification = c(1, 0), legend.position = c(0.99, 0.02))

# leaf area and LAI
ggplot(individualTreeSubset) +
  geom_line(aes(x = year, y = leafArea, color = species, group = id), alpha = 0.3, arrow = arrow(length = unit(0.25, "line"), type = "closed")) +
  labs(x = "calendar year", y = bquote("tree leaf area, m"^2), color = NULL) +
  scale_x_continuous(breaks = seq(2022, 2032, by = 2)) +
  theme(legend.justification = c(0, 1), legend.position = c(0.02, 0.99))
ggplot(elliottResourceUnitTrajectories) + 
  geom_path(aes(x = year, y = lai, color = species, group = paste(resourceUnit, species)), alpha = 0.5) +
  labs(x = "calendar year", y = bquote("resource unit LAI, m"^2*" m"^-2), color = NULL) +
  scale_x_continuous(breaks = seq(2022, 2032, by = 2))
ggplot(elliottStandTrajectories) +
  geom_path(aes(x = year, y = lai, group = stand), alpha = 0.5) +
  labs(x = "calendar year", y = bquote("stand LAI, m"^2*" m"^-2), color = NULL) +
  scale_x_continuous(breaks = seq(2022, 2032, by = 2))

# NPP
ggplot(individualTreeSubset) +
  geom_line(aes(x = year, y = nppReserve, color = species, group = id), alpha = 0.3) +
  labs(x = "calendar year", y = "tree NPP reserve, kg biomass", color = NULL) +
  scale_x_continuous(breaks = seq(2022, 2032, by = 2)) +
  theme(legend.justification = c(0, 1), legend.position = c(0.02, 0.99))
ggplot(elliottResourceUnitTrajectories %>% filter(species == "all") %>% filter(year > 2021)) + # no NPP estimates in year before timestepping starts
  geom_path(aes(x = year, y = treeNpp, color = "tree NPP, total", group = resourceUnit), alpha = 0.5) +
  geom_path(aes(x = year, y = treeAbovegroundNpp, color = "tree NPP, aboveground", group = resourceUnit), alpha = 0.5) +
  geom_path(aes(x = year, y = saplingNpp, color = "sapling NPP, total", group = resourceUnit), alpha = 0.5) +
  labs(x = "calendar year", y = bquote("resource unit NPP, kg biomass ha"^-1), color = NULL) +
  scale_color_discrete(breaks = c("tree NPP, total", "tree NPP, aboveground", "sapling NPP, total")) +
  scale_x_continuous(breaks = seq(2022, 2032, by = 2)) +
  theme(legend.justification = c(1, 1), legend.position = c(0.99, 0.99))
ggplot(elliottStandTrajectories %>% filter(year > 2021)) +
  geom_path(aes(x = year, y = treeNpp, color = "tree NPP, total", group = stand), alpha = 0.5) +
  geom_path(aes(x = year, y = treeAbovegroundNpp, color = "tree NPP, aboveground", group = stand), alpha = 0.5) +
  geom_path(aes(x = year, y = saplingNpp, color = "sapling NPP, total", group = stand), alpha = 0.5) +
  labs(x = "calendar year", y = bquote("stand NPP, kg biomass ha"^-1), color = NULL) +
  scale_color_discrete(breaks = c("tree NPP, total", "tree NPP, aboveground", "sapling NPP, total")) +
  scale_x_continuous(breaks = seq(2022, 2032, by = 2)) +
  theme(legend.justification = c(1, 1), legend.position = c(0.99, 0.99))

# saplings: these are all zero if 1) no saplings in initial stand state and 2) regeneration isn't enabled
ggplot(elliottResourceUnitTrajectories %>% filter(species = "psme")) +
  geom_path(aes(x = year, y = saplingCohorts, color = "cohorts", group = resourceUnit), alpha = 0.5) +
  geom_path(aes(x = year, y = saplingMeanAge, color = "mean age", group = resourceUnit), alpha = 0.5) +
  geom_path(aes(x = year, y = saplingNpp, color = "NPP", group = resourceUnit), alpha = 0.5) +
  geom_path(aes(x = year, y = saplingsPerHectare, color = "saplings", group = resourceUnit), alpha = 0.5) +
  labs(x = "calendar year", y = "resource unit saplings", color = NULL) +
  scale_color_discrete(breaks = c("saplings", "cohorts", "mean age", "NPP"), labels = c(bquote("saplings ha"^-1), bquote("cohorts ha"^-1), "mean age, years", bquote("NPP, kg ha"^-1))) +
  scale_x_continuous(breaks = seq(2022, 2032, by = 2)) +
  theme(legend.justification = c(1, 1), legend.position = c(0.99, 0.99))
ggplot(elliottStandTrajectories) +
  geom_path(aes(x = year, y = saplingCohorts, color = "cohorts", group = stand), alpha = 0.5) +
  geom_path(aes(x = year, y = saplingMeanAge, color = "mean age", group = stand), alpha = 0.5) +
  geom_path(aes(x = year, y = saplingNpp, color = "NPP", group = stand), alpha = 0.5) +
  geom_path(aes(x = year, y = saplingsPerHectare, color = "saplings", group = stand), alpha = 0.5) +
  labs(x = "calendar year", y = "stand saplings", color = NULL) +
  scale_color_discrete(breaks = c("saplings", "cohorts", "mean age", "NPP"), labels = c(bquote("saplings ha"^-1), bquote("cohorts ha"^-1), "mean age, years", bquote("NPP, kg ha"^-1))) +
  scale_x_continuous(breaks = seq(2022, 2032, by = 2)) +
  theme(legend.justification = c(1, 1), legend.position = c(0.99, 0.99))

# biomass components
ggplot(individualTreeSubset) +
  geom_line(aes(x = year, y = coarseRootMass, color = "coarse root", group = id), alpha = 0.2) +
  geom_line(aes(x = year, y = fineRootMass, color = "fine root", group = id), alpha = 0.2) +
  geom_line(aes(x = year, y = foliageMass, color = "foliage", group = id), alpha = 0.2) +
  geom_line(aes(x = year, y = stemMass, color = "stem", group = id), alpha = 0.2) +
  labs(x = "calendar year", y = "tree component, kg biomass", color = NULL) +
  guides(color = guide_legend(ncol = 4)) +
  scale_x_continuous(breaks = seq(2022, 2032, by = 2)) +
  scale_y_log10() +
  theme(legend.justification = c(0, 1), legend.position = c(0.02, 0.99))
ggplot(elliottResourceUnitTrajectories %>% filter(species == "all")) + # in rough order from largest to smallest pools
  geom_path(aes(x = year, y = 0.001 * stemCarbon, color = "stem", group = resourceUnit), alpha = 0.5) +
  geom_path(aes(x = year, y = 0.001 * coarseRootCarbon, color = "coarse root", group = resourceUnit), alpha = 0.5) +
  geom_path(aes(x = year, y = 0.001 * branchCarbon, color = "branch", group = resourceUnit), alpha = 0.5) +
  geom_path(aes(x = year, y = 0.001 * foliageCarbon, color = "foliage", group = resourceUnit), alpha = 0.5) +
  geom_path(aes(x = year, y = 0.001 * fineRootCarbon, color = "fine root", group = resourceUnit), alpha = 0.5) +
  #geom_path(aes(x = year, y = 0.001 * regenerationCarbon, color = "regeneration", group = resourceUnit), alpha = 0.5) + # zero if no saplings
  guides(color = guide_legend(ncol = 7)) +
  labs(x = "calendar year", y = bquote("resource unit carbon, Mg ha"^-1), color = NULL) +
  scale_x_continuous(breaks = seq(2022, 2032, by = 2)) +
  scale_y_log10() +
  theme(legend.justification = c(0.5, 0), legend.position = c(0.53, 0.02))
ggplot(elliottResourceUnitTrajectories %>% filter(species = "psme")) + # in rough order from largest to smallest pools
  geom_path(aes(x = year, y = stemNitrogen, color = "stem", group = resourceUnit), alpha = 0.5) +
  geom_path(aes(x = year, y = coarseRootNitrogen, color = "coarse root", group = resourceUnit), alpha = 0.5) +
  geom_path(aes(x = year, y = branchNitrogen, color = "branch", group = resourceUnit), alpha = 0.5) +
  geom_path(aes(x = year, y = foliageNitrogen, color = "foliage", group = resourceUnit), alpha = 0.5) +
  geom_path(aes(x = year, y = fineRootNitrogen, color = "fine root", group = resourceUnit), alpha = 0.5) +
  #geom_path(aes(x = year, y = regenerationNitrogen, color = "regeneration", group = resourceUnit), alpha = 0.5) + # zero if no saplings
  guides(color = guide_legend(ncol = 7)) +
  labs(x = "calendar year", y = bquote("resource unit nitrogen, kg ha"^-1), color = NULL) +
  scale_x_continuous(breaks = seq(2022, 2032, by = 2)) +
  scale_y_log10() +
  theme(legend.justification = c(0.5, 0), legend.position = c(0.53, 0.02))

# tree lighting and stress response
ggplot(individualTreeSubset) +
  geom_line(aes(x = year, y = lightResourceIndex, color = species, group = id), alpha = 0.3) +
  labs(x = NULL, y = "light resource index", color = NULL) +
  scale_x_continuous(breaks = seq(2022, 2032, by = 2)) +
  theme(legend.position = "none") +
ggplot(individualTreeSubset) +
  geom_line(aes(x = year, y = opacity, color = species, group = id), alpha = 0.3) +
  labs(x = NULL, y = "opacity", color = NULL) +
  scale_x_continuous(breaks = seq(2022, 2032, by = 2)) +
  theme(legend.position = "none") +
ggplot(individualTreeSubset) +
  geom_line(aes(x = year, y = lightResponse, color = species, group = id), alpha = 0.3) +
  labs(x = "calendar year", y = "light response", color = NULL) +
  scale_x_continuous(breaks = seq(2022, 2032, by = 2)) +
  theme(legend.position = "none") +
ggplot(individualTreeSubset) +
  geom_line(aes(x = year, y = stressIndex, color = species, group = id), alpha = 0.3) +
  labs(x = "calendar year", y = "stress index", color = NULL) +
  scale_x_continuous(breaks = seq(2022, 2032, by = 2)) +
  theme(legend.justification = c(0, 1), legend.position = c(0.02, 0.99))
